const sentences = [
  "The stars weep in colors no eye has ever seen.",
  "Beneath the silver moon, whispers gather in the fog.",
  "A shadow folds itself into the shape of your name.",
  "The forest hums a hymn older than time.",
  "Lightning sleeps beneath the petals of forgotten flowers.",
  "A river of ink flows through the veins of the sky.",
  "Time trembles when it sees its own reflection.",
  "The mountain remembers the footsteps that never were.",
  "An unseen choir sings through the cracks of reality.",
  "The wind folds secrets into every falling leaf.",
  "A lantern flickers in a hallway that stretches forever.",
  "The ocean hides voices that belong to no one.",
  "Snow falls upward in the hollow of forgotten worlds.",
  "Eyes form in clouds, watching the stories below.",
  "The horizon bends when the dreamer closes their eyes.",
  "A clock ticks in a room where time does not exist.",
  "Shadows paint murals on walls that do not exist.",
  "The roses hum songs they never learned.",
  "Stars drip like honey across the velvet night.",
  "A river of glass reflects moons that were never born.",
  "The silence in the woods holds more than whispers.",
  "Mirrors sigh when no one looks into them.",
  "A candle burns in a room that waits for nothing.",
  "The sky folds into itself like a secret letter.",
  "Clouds breathe in patterns of forgotten languages.",
  "Lanterns float above streets that twist endlessly.",
  "The library of shadows catalogs thoughts unseen.",
  "Mountains whisper to the rivers that flow within them.",
  "The fog carries laughter that echoes from nowhere.",
  "A butterfly lands where time once paused.",
  "The walls remember the footsteps of dreams.",
  "Rain hums hymns that the earth cannot hear.",
  "A key turns in a door that opens to nowhere.",
  "The moon bends low to hear the songs of the sea.",
  "A lantern swings in corridors of liquid silver.",
  "The air tastes of memories not yet lived.",
  "Branches twist into letters the wind can read.",
  "The ocean hums riddles to the sands of eternity.",
  "Stars drift into patterns that speak in silence.",
  "The mountain folds its shadows into hidden rooms.",
  "A bell rings where no ears can listen.",
  "The sky holds its breath above the forgotten valley.",
  "Mist curls around secrets too fragile to speak.",
  "The forest exhales memories it never owned.",
  "A path winds through dreams that refuse to awaken.",
  "Lanterns float, lighting corridors of infinite dusk.",
  "Time whispers in the spaces between heartbeats.",
  "The horizon trembles under the weight of forgotten suns.",
  "A song rises from the ruins of unseen cities.",
  "The wind carries words that vanish before being heard.",
  "The river bends itself into shapes of lost names.",
  "A shadow walks where the light fears to tread.",
  "The stars remember what the night tries to hide.",
  "Fog settles like dust on the bones of the earth.",
  "The moon spills silver tears into the silent forest.",
  "Each leaf cradles the echo of a vanished thought.",
  "A forgotten door opens to a corridor of whispers.",
  "The clouds bleed violet into the dying sky.",
  "A lantern waits at the edge of a memory you lost.",
  "The wind traces letters on windows no one reads.",
  "Time hides beneath the roots of ancient trees.",
  "The lake mirrors faces that were never alive.",
  "Shadows grow long when the horizon forgets its shape.",
  "A hummingbird carries the weight of old secrets.",
  "The night hums in colors that the mind cannot name.",
  "The cathedral of stars kneels before an empty throne.",
  "A door closes where no one remembers leaving it.",
  "Mist drifts through the alleys of forgotten cities.",
  "The river hums an elegy for forgotten dreams.",
  "Stars bleed into rivers that lead nowhere.",
  "A forgotten bell tolls in the silence of the hills.",
  "The wind gathers the whispers of uncounted souls.",
  "Lanterns flicker in the corridors of lost time.",
  "The horizon folds in upon itself like a secret note.",
  "Mountains hum beneath the weight of unseen suns.",
  "The moon listens to the heartbeat of the world.",
  "Branches twist into faces that vanish when you stare.",
  "A candle flickers in a room that breathes with shadows.",
  "The fog tastes of memories that never belonged to you.",
  "A river bends around the shape of an ancient sigh.",
  "The night trembles at the edge of forgotten dreams.",
  "Stars whisper stories that no living mind can hold.",
  "The wind hums a hymn older than the mountains.",
  "Mist coils into letters the mind cannot decipher.",
  "Lanterns float above seas of forgotten thoughts.",
  "Time folds silently into the hollows of the world.",
  "The forest holds its breath under a violet sky.",
  "A shadow drifts across the face of an unlit moon.",
  "The horizon sighs with the weight of endless nights.",
  "The lake mirrors the void of unspoken words.",
  "Branches sway to music that the wind alone remembers.",
  "The candle hums with a song the mind cannot hear.",
  "Time sleeps beneath the petals of invisible flowers.",
  "Mist drapes the mountains in veils of forgotten light.",
  "Lanterns swing above paths that lead to nowhere.",
  "The horizon folds into itself like a whispered memory.",
  "Stars tremble at the edge of forgotten skies.",
  "The wind carries stories no one remembers hearing.",
  "Shadows gather where the night swallows the sun.",
  "A river winds through the hollows of silent mountains.",
  "The forest exhales whispers into the endless dark.",
  "Fog drifts over the remnants of vanished cities.",
  "The moon hums a lullaby older than the stars.",
  "Branches twist into letters that vanish when read.",
  "The candle burns with secrets the world forgot.",
  "Time bends around the corners of forgotten valleys.",
  "Lanterns float through corridors that lead to forgotten dreams.",
  "Stars weep into the river of endless night.",
  "The wind hums through the alleys of vanished worlds.",
  "Mist folds itself into shapes only the mind dares see.",
  "The horizon trembles beneath the weight of forgotten stars.",
  "Shadows dance across the surface of silent lakes.",
  "A door opens to a hallway of unspoken words.",
];

document.getElementById("generateBtn").addEventListener("click", () => {
  const random = sentences[Math.floor(Math.random() * sentences.length)];
  document.getElementById("output").textContent = random;
  
  // Create a sparkle effect
  createSparkle();
});

// Function to create sparkles
function createSparkle() {
  const sparkle = document.createElement("div");
  sparkle.className = "sparkle";
  sparkle.style.left = Math.random() * window.innerWidth + "px";
  sparkle.style.top = Math.random() * window.innerHeight + "px";
  document.body.appendChild(sparkle);
  
  setTimeout(() => {
    sparkle.remove();
  }, 6000); // matches float animation duration
}